apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-database
  labels:
    app: api-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-database
  template:
    metadata:
      labels:
        app: api-database
    spec:
      containers:
        - name: api-database
          image: mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: api-database
  labels:
    app: api-database
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: api-database