apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      restartPolicy: Always
      containers:
        - name: order-service
          image: milanuzelac/kubernetes-order
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      nodePort: 30005
  selector:
    app: order-service